# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nicholaslong.org
title: Nicholas Long
email: your-email@domain.com
author: Nicholas Long
description: > # ""
copyright: 'Copyright &copy; 2016 Nicholas Long. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/nllong
  - title: github
    url: https://github.com/nllong
  - title: linkedin
    url: https://www.linkedin.com/in/nllong
