permissions:
  id-token: write
  contents: read
  pages: write
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Jekyll
        run: |
          gem install jekyll

      - name: Build Jekyll site
        run: |
          jekyll build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
